In [1]:
import transformers
import pandas
import numpy
import torch
import json

/home/jerko/.local/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
dataset = pandas.read_parquet('raw_data/RACE/validation-00000-of-00001.parquet')

In [3]:
dataset

example_id                                            article  \
0       high5060.txt  I am a psychologist. I first met Timothy, a qu...   
1       high5060.txt  I am a psychologist. I first met Timothy, a qu...   
2       high5060.txt  I am a psychologist. I first met Timothy, a qu...   
3      high14410.txt  From self-driving cars to carebots (care+robot...   
4      high14410.txt  From self-driving cars to carebots (care+robot...   
...              ...                                                ...   
4882  middle5525.txt  John and Jack met at the old bench every after...   
4883  middle5525.txt  John and Jack met at the old bench every after...   
4884  middle7740.txt  Everyone has got two personalities --- the one...   
4885  middle7740.txt  Everyone has got two personalities --- the one...   
4886  middle7740.txt  Everyone has got two personalities --- the one...   

     answer                                           question  \
0         C  What did the writer think of Timothy after lea...   
1         A  Which of the following statements best describ...   
2         C  According to the passage, how long should a th...   
3         A                    According to the report,   _  .   
4         B  We can infer from the text that in the future ...   
...     ...                                                ...   
4882      B   John sat on the beach and probably waited for  _   
4883      C            What is the best title for the passage?   
4884      A               You may find this passage in   _   .   
4885      B  Tina hardly tells her secrets to her friends ....   
4886      C                    What does the passage tell us ?   

                                                options  
0     [Timothy was very hardworking., Timothy was be...  
1     [Children should be allowed enough time to pla...  
2     [About ten minutes., No more than twenty minut...  
3     [people won't necessarily lose jobs, big compa...  
4     [people will face many difficulties, people wi...  
...                                                 ...  
4882              [his mother, Jack, Steven, his uncle]  
4883  [A birthday present, A football match, A home-...  
4884  [a science magazine, A shopping guide book, a ...  
4885  [curled up, on her stomach, on her back, on he...  
4886  [Sleeping on you side is the best way of sleep...  

[4887 rows x 5 columns]

In [4]:
dataset['question'][365]

'With a "Fast Lane" card, visitors can   _  .'

In [5]:
with open('raw_data/ReCoRD/train.json') as f:
    record_dataset = json.load(f)

In [6]:
record_dataset = pandas.DataFrame(record_dataset['data'])

In [7]:
record_dataset

id      source  \
0      536e2fdfb3c986efa15da314b0df2d2d218cf693  Daily mail   
1      f15689cd256daa03fcfd8c357f1376a8a7017b64         CNN   
2      bd4f4fd84a92411a7c03fe80fa2e84270ac51ac3  Daily mail   
3      16f4d0c2b42cfd57557d1aaf398110ebf519874f  Daily mail   
4      a204b0da2b9a5267a0527632ab8d5691b2c412de  Daily mail   
...                                         ...         ...   
65704  6079a996b955d3130ad59c37b57d9958e0539b83  Daily mail   
65705  4e466fabc27adf6cb2180c8441f9b0d5266062ba  Daily mail   
65706  cc54a42ae756fa5bddda37e91948149793bd072b         CNN   
65707  5c6f7eec2a86ccd30d412c24f90f4c1e91aa607b         CNN   
65708  c12e2c7c36bd87b7b34dead0a18231431f7fcdaa  Daily mail   

                                                 passage  \
0      {'text': 'The harrowing stories of women and c...   
1      {'text': 'Caracas, Venezuela (CNN) -- It's bee...   
2      {'text': 'U.S. Secretary of State Henry Kissin...   
3      {'text': 'A Peruvian tribe once revered by the...   
4      {'text': 'For everyone who has ever thought ab...   
...                                                  ...   
65704  {'text': 'Liverpool are ready to revive their ...   
65705  {'text': 'A Russian tourist has been hospitali...   
65706  {'text': 'Editor's note: Ilya Shapiro is a sen...   
65707  {'text': '(CNN) -- Newt Gingrich quit the pres...   
65708  {'text': 'By Kieran Gill Anton Ferdinand has s...   

                                                     qas  
0      [{'id': '536e2fdfb3c986efa15da314b0df2d2d218cf...  
1      [{'id': 'f15689cd256daa03fcfd8c357f1376a8a7017...  
2      [{'id': 'bd4f4fd84a92411a7c03fe80fa2e84270ac51...  
3      [{'id': '16f4d0c2b42cfd57557d1aaf398110ebf5198...  
4      [{'id': 'a204b0da2b9a5267a0527632ab8d5691b2c41...  
...                                                  ...  
65704  [{'id': '6079a996b955d3130ad59c37b57d9958e0539...  
65705  [{'id': '4e466fabc27adf6cb2180c8441f9b0d526606...  
65706  [{'id': 'cc54a42ae756fa5bddda37e91948149793bd0...  
65707  [{'id': '5c6f7eec2a86ccd30d412c24f90f4c1e91aa6...  
65708  [{'id': 'c12e2c7c36bd87b7b34dead0a18231431f7fc...  

[65709 rows x 4 columns]

In [8]:
record_dataset['passage'][0]

{'text': "The harrowing stories of women and children locked up for so-called 'moral crimes' in Afghanistan's notorious female prison have been revealed after cameras were allowed inside. Mariam has been in Badam Bagh prison for three months after she shot a man who just raped her at gunpoint and then turned the weapon on herself - but she has yet to been charged. Nuria has eight months left to serve of her sentence for trying to divorce her husband. She gave birth in prison to her son and they share a cell together. Scroll down for video Nuria was jailed for trying to divorce her husband. Her son is one of 62 children living at Badam Bagh prison\n@highlight\nMost of the 202 Badam Bagh inmates are jailed for so-called 'moral crimes'\n@highlight\nCrimes include leaving their husbands or refusing an arrange marriage\n@highlight\n62 children live there and share cells with their mothers and five others",
 'entities': [{'start': 86, 'end': 96},
  {'start': 178, 'end': 183},
  {'start': 197

In [9]:
filtered_rows = record_dataset[record_dataset['id'] == '6079a996b955d3130ad59c37b57d9958e0539b83']
filtered_rows

id      source  \
65704  6079a996b955d3130ad59c37b57d9958e0539b83  Daily mail   

                                                 passage  \
65704  {'text': 'Liverpool are ready to revive their ...   

                                                     qas  
65704  [{'id': '6079a996b955d3130ad59c37b57d9958e0539...

In [10]:
fl = list(filter(lambda x: len(x) > 1, (record_dataset['qas'])))

In [11]:
len(fl)

21442

In [12]:
with open('raw_data/multirc-v2/splitv2/train_456-fixedIds.json') as f:
    rc_dataset = json.load(f)

In [13]:
rc_dataset = pandas.DataFrame(rc_dataset['data'])

In [14]:
rc_dataset

paragraph  \
0    {'text': '<b>Sent 1: </b>Animated history of t...   
1    {'text': '<b>Sent 1: </b>Before the mysterious...   
2    {'text': '<b>Sent 1: </b>Hotel California My f...   
3    {'text': '<b>Sent 1: </b>Elaan is a declaratio...   
4    {'text': '<b>Sent 1: </b>Not until 1998 did al...   
..                                                 ...   
451  {'text': '<b>Sent 1: </b>How would the univers...   
452  {'text': '<b>Sent 1: </b>Once upon a time ther...   
453  {'text': '<b>Sent 1: </b>In her storage room-t...   
454  {'text': '<b>Sent 1: </b>A West Tennessee nonp...   
455  {'text': '<b>Sent 1: </b>U.S. Secretary of Sta...   

                                                    id  
0    Society_Law_and_Justice/masc-A_defense_of_Mich...  
1    News/CNN/cnn-3b372dbbdea7cabac969352b8b3169a0e...  
2          Fiction-stories-masc-hotel-California-1.txt  
3                      wikiMovieSummaries-27380172.txt  
4                  Sept11-reports/oanc-chapter-2-5.txt  
..                                                 ...  
451                 Science-textbook/science-g3-31.txt  
452                   Fiction/mctest-mc160.dev.5-0.txt  
453  Society_Law_and_Justice/oanc-Crains_New_York_B...  
454  Society_Law_and_Justice/oanc-fight_domestic_ab...  
455                   News/NYT/masc-20020731-nyt-4.txt  

[456 rows x 2 columns]

In [15]:
rc_dataset['paragraph'][0].keys()

dict_keys(['text', 'questions'])

In [16]:
import re

text = rc_dataset['paragraph'][0]['text']

pattern = r"<b>Sent \d+: </b>(.*?)<br>"
sentences = re.findall(pattern, text)

# Print the sentences
for i, sentence in enumerate(sentences, 1):
    print(f"Sentence {i}: {sentence}")


Sentence 1: Animated history of the US.
Sentence 2: Of course the cartoon is highly oversimplified, and most critics consider it one of the weakest parts of the film.
Sentence 3: But it makes a valid claim which you ignore entirely: That the strategy to promote "gun rights" for white people and to outlaw gun possession by black people was a way to uphold racism without letting an openly terrorist organization like the KKK flourish.
Sentence 4: Did the 19th century NRA in the southern states promote gun rights for black people?
Sentence 5: I highly doubt it.
Sentence 6: But if they didn't, one of their functions was to continue the racism of the KKK.
Sentence 7: This is the key message of this part of the animation, which is again being ignored by its critics.
Sentence 8: Buell shooting in Flint.
Sentence 9: You write: "Fact: The little boy was the class thug, already suspended from school for stabbing another kid with a pencil, and had fought with Kayla the day before".
Sentence 10: Th

In [17]:
rc_dataset['paragraph'][6]['questions'][5]

{'question': 'After what successfully won battle was Philip named "Hegemon"',
 'sentences_used': [9, 10, 1, 8],
 'answers': [{'text': 'Modern scholars', 'isAnswer': False, 'scores': {}},
  {'text': 'The battle of Sparta', 'isAnswer': False, 'scores': {}},
  {'text': 'Battle of Chaeronea', 'isAnswer': True, 'scores': {}}],
 'idx': '5',
 'multisent': True}

In [18]:
with open('raw_data/BoolQ/train.jsonl') as f:
    boolq_dataset = f.readlines()

boolq_dataset = pandas.DataFrame([json.loads(x) for x in boolq_dataset])

In [19]:
boolq_dataset

question  \
0       do iran and afghanistan speak the same language   
1     do good samaritan laws protect those who help ...   
2     is windows movie maker part of windows essentials   
3     is confectionary sugar the same as powdered sugar   
4            is elder scrolls online the same as skyrim   
...                                                 ...   
9422             is a us district court a federal court   
9423  can a tenant get a restraining order against a...   
9424       is the golden state warriors in the playoffs   
9425             downton abbey will there be a season 7   
9426  is margin of error the same as confidence inte...   

                               title  answer  \
0                   Persian language    True   
1                 Good Samaritan law    True   
2                Windows Movie Maker    True   
3                     Powdered sugar    True   
4           The Elder Scrolls Online   False   
...                              ...     ...   
9422    United States district court    True   
9423             Landlord harassment    True   
9424           Golden State Warriors    True   
9425  List of Downton Abbey episodes   False   
9426                 Margin of error   False   

                                                passage  
0     Persian (/ˈpɜːrʒən, -ʃən/), also known by its ...  
1     Good Samaritan laws offer legal protection to ...  
2     Windows Movie Maker (formerly known as Windows...  
3     Powdered sugar, also called confectioners' sug...  
4     As with other games in The Elder Scrolls serie...  
...                                                 ...  
9422  The United States district courts are the gene...  
9423  If a landlord is found to be retaliating, he o...  
9424  The Warriors went into the 2018 playoffs as th...  
9425  Downton Abbey is a British period drama televi...  
9426  The margin of error is usually defined as the ...  

[9427 rows x 4 columns]

In [20]:
boolq_dataset['answer'][42] == False

True

In [21]:
from datasets import Boolq_dataset
from dataset_loaders import load_boolq
from transformers import GPT2Tokenizer

boolq_dataset = load_boolq("raw_data/BoolQ/train.jsonl", GPT2Tokenizer.from_pretrained('gpt2'))


In [22]:
boolq_dataset[435]

(tensor([[  464,   477, 23823, 35733, 28699,   357, 14155,   305,  2395, 27385,
           2169,  1084,   694,  4178,     8,   318,   257,  4693,   286, 28699,
            287,   262,  1641,  2580,   306,    67,  6058,  3609,    11,  6868,
            284, 40941, 35308,   287,   262,  1578,  1829,    13,   337,    13,
           2169,  1084,   694,  4178,   318,   530,   286,   262, 45568, 40941,
          36288,   287,   262,   995,    13,   632,   318,  1690,  3917,   351,
             11,   475,   407,  7173,  3519,   284,    11,   262,  2219, 35733,
          28699,    11,   543,   318,   287,   262, 34306,  2580,   306, 32491,
             13,   383,  2176, 21240,  3202,  2169,  1084,   694,  4178,   318,
            287,  7522,   286, 10914, 40565,  7451,  1766,   268,   430,   324,
          12806,  5825,  1084,   694,    13,   271,   612,   884,  1517,   355,
            281,   477, 23823, 35733, 28699,    30,  3363,    13]]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [23]:
from datasets import MultiRC_dataset
from dataset_loaders import load_multirc
from transformers import GPT2Tokenizer

multirc_dataset = load_multirc("raw_data/multirc-v2/splitv2/train_456-fixedIds.json", GPT2Tokenizer.from_pretrained('gpt2'))

In [24]:
multirc_dataset[56]

(tensor([[37136,   337,   364,    71,   505,   550,   645,  8722,   287, 19732,
            465,  2650,   618, 13612,  1625,   319,  7077,   379,  2237,   267,
              6, 15750,    13,  1544,  1444,   510,   257, 16212,   290,  1816,
            379,  1752,   284,   465,  9519,   379,   262,  8274,   742, 13485,
             26,   290, 33381,   263,   774,  3940,   683,    13,  3633,   339,
          25148,   465,  6576,    12, 31434,    11,  1718,   257,  7837,   290,
            836,  2817,   465,  6155,  6050,   337,   364,    71,   505,   373,
            287,   257,  7586,  2050,    13, 39792,  2084, 31774,   550,   587,
          11512, 11406,   379,   262,  3687, 11942,  2156,   290,  4624,   287,
            262,  1337,   286,  1468, 43116, 17419,   786,    11,   508,   561,
           4860,   607,   588,   281, 47656,    13,  1858,   373,   645,  7103,
            761,   286,   465, 19338,  3101,   706,   607,    11,   290,   465,
           3251,   290,   262,  9412,   

In [25]:
multirc_dataset.question_answer_objs[0].question

'Does the author claim the animated films message is that the NRA upholds racism?'

In [26]:
multirc_dataset.passages[0]

['Animated history of the US.',
 'Of course the cartoon is highly oversimplified, and most critics consider it one of the weakest parts of the film.',
 'But it makes a valid claim which you ignore entirely: That the strategy to promote "gun rights" for white people and to outlaw gun possession by black people was a way to uphold racism without letting an openly terrorist organization like the KKK flourish.',
 'Did the 19th century NRA in the southern states promote gun rights for black people?',
 'I highly doubt it.',
 "But if they didn't, one of their functions was to continue the racism of the KKK.",
 'This is the key message of this part of the animation, which is again being ignored by its critics.',
 'Buell shooting in Flint.',
 'You write: "Fact: The little boy was the class thug, already suspended from school for stabbing another kid with a pencil, and had fought with Kayla the day before".',
 "This characterization of a six-year-old as a pencil-stabbing thug is exactly the kind

In [27]:
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
tokenizer.decode([  1029, 2009, 8440, 1005,
         1056, 6003, 2007, 2200, 2204, 7022,  102])

' high investig shipping rethipaintsitchRE benef island�'

In [28]:
a = "bal bla    bla _ bla"
tokenizer.encode(a[:a.index("_")], add_special_tokens=False)

[6893, 698, 64, 220, 220, 220, 698, 64, 220]

In [29]:
tokenizer.decode(  [101, 28352, 1038, 2721, 1038, 2721, 1035, 1038, 2721, 102])

'�usra requ install requ install ins requ install�'

In [30]:
from datasets import ReCoRD_dataset
from dataset_loaders import load_race

race_dataset = load_race("raw_data/RACE/validation-00000-of-00001.parquet", GPT2Tokenizer.from_pretrained('gpt2'))

In [31]:
import numpy as np
a = np.random.randint(4000)

print(a)
print(race_dataset[a][1][-20:])
print(race_dataset[a][2][-20:])

3556
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0])
tensor([-100, -100, -100, -100, -100, -100, -100, -100, -100,  356,  815, 2193,
         284, 1842, 1123,  584,  220, -100, -100, -100])


In [32]:
race_dataset[3679]

(tensor([[23722,   345,   307,   257, 15632,   588, 24572,    30,   317, 15632,
           2476,   284,  2193,   290,   892,    13, 11725,   318,   257,   922,
           2126,    11,   475,   340,   318,   407,  1576,    13, 24572,   338,
           5608,   318,   284,   779,   534,  3632,   517,    13,  3423,   389,
            617,  9040,    25,   198,    75, 16981,    13,  1649,   345,   804,
            379,   649,  1243,    11,  1265,  1521,   484,   389,   649,   393,
           1180,    13, 16981,   517,  2683,    13, 16981,  3511,   290,  1854,
             13,  9175,  3612,  1566,   345,  1064,   262,  7429,    13,   198,
             75, 15315,    13, 24572,  1807,   287,  5986,    13,  8975,    11,
            340,  5419,   284,  3197,  2761,   290,  4213,    13,   198,    75,
           4149,    13,  9993,   284,  1100,   649,  1243,    13,  4149,  3835,
            422,  1180,  3354,   286,   262,  5888,    13,  2293,   345,  1100,
             11,   892,   546,   262,  4

In [33]:
tokenizer.decode([6848, 1996, 4784, 2007, 2500])

' admittedput Accordingitchicro'

In [34]:
tokenizer.decode([1013])

' conf'

In [35]:
import os
import pandas as pd
import json
import re
from typing import Type, TypeVar
from typing import Tuple, Union, Literal, List, Dict
from transformers import AutoTokenizer

In [36]:
from datasets import ReCoRD_dataset
from dataset_loaders import load_record
dataset_record = load_record(path="raw_data/ReCoRD/train.json", tokenizer=GPT2Tokenizer.from_pretrained('gpt2'))

In [37]:
dataset_record[13]

(tensor([[ 9914, 40263,    11, 16666,   357, 18474,     8,  1377,   632,   338,
            587,   517,   621, 11546,   812,  1201, 13420,   504,  2497, 11288,
          10797,   452,   283,   338,  1986,    13,   887,   262, 12253,  3554,
            338,  6546,  1735, 10899,    82,    11,  1323, 12114, 26928,   290,
            336, 45269, 17841, 22928,   503,   422,  2157,  4286, 13431,  3431,
            287,   649,   513,    12,    35,  4263, 18475,   416,  1992, 25930,
          31039,    13, 26685,   973,  1811,  3788,  4056,   284, 31081,   262,
           1986,   286,   262,   582,   508, 35112, 38496,    11, 21291,    11,
          25794,    11, 23519,    11, 25768,   290, 16666,   422,   262,  7897,
          12389,    13,  1446,   504,   286, 10797,   452,   283,   338, 30142,
           3793,    11,   543, 10093,   409, 17047,   276,   734,   812,  2084,
             11,  1109,  1850,   656,   511, 16765,    13,  1406,   750,  6754,
          21641,    11,  5205,   286, 15

In [38]:
load_boolq("raw_data/BoolQ/train.jsonl", GPT2Tokenizer.from_pretrained('gpt2'))

In [39]:
ds = load_record("raw_data/ReCoRD/train.json", GPT2Tokenizer.from_pretrained('gpt2'))

In [40]:
print(ds[24][0])
print(ds[24][2])

tensor([[   52,    13,    50,    13,  4986,   286,  1812,  8616, 39162,  6149,
         38820,  3352,  7428,   510,  3016,  2319,   812,  2084,   284,  1368,
         14159,    11,   753, 15385,   625,   262,  1402,  7022,   338, 14833,
           286,  6553,   284, 48968,    11,  1864,   284, 42794,  1431,  1230,
          4963,  4481,  2691,  3583,    13,   554,  1811,  2635,  2097,  8292,
            11, 39162, 25828,   329,  1913,  2223,   284,  2245, 21193,    11,
         26844,   326,   465,   753, 24197,   287,  5478,   373,  1642,   262,
           471,    13,    50,    13,   804,  4939,    13,   679,  7189,   326,
         14159,   338,  4028,   547,  5059, 10251,  1088,   262,   995,   286,
           257, 10595,  3234,  1175,   326,   714, 19431,   625,   656,  9133,
          2253,   290,   772, 27397,  1096,   262,  6046,  3687,    13,   554,
           257,  2168,   286, 38820,  3352,   326,  3940,    11,  3689, 17929,
           422,   257,  2422, 30974,   284, 26665,  

In [41]:
tokenizer.decode([ 1057,  1012,  1055,  1012,  3187,  1997,  2110,  2888,  7618,  2121,
          3641,  9530,  3436, 11916,  3488,  4567,  2039,  3053,  2871,  2086,
          3283,  2000,  2886,  7394,  1010, 28647,  2094,  2058,  1996,  2235,
          2479,  1005,  1055, 10813,  1997,  3629,  2000, 13491,  1010,  2429,
          2000, 11703, 24938,  2231,  5491,  6866,  3784,  9317,  1012,  1999,
          2195,  2317,  2160,  6295,  1010,  7618,  2121, 11886,  2005,  2844,
          2895,  2000,  2644, 11794,  1010, 19725,  2008,  2010,  4297,  9236,
          3258,  1999,  3088,  2001,  2437,  1996,  1057,  1012,  1055,  1012,
          2298,  5410,  1012,  2002,  5275,  2008,  7394,  1005,  1055,  4506,
          2020,  4439, 10069,  2105,  1996,  2088,  1997,  1037,  7289,  2679,
          2162,  2008,  2071, 14437,  2058,  2046,  3763,  2637,  1998,  2130,
          4078,  2696, 14454,  4697,  1996,  2690,  2264,  1012,  1999,  1037,
          2186,  1997,  9530,  3436, 11916,  3488,  2008,  2628,  1010,  7047,
         15844,  2013,  1037,  2510, 15823,  2000, 14369, 18886,  9681,  1998,
          5471,  1997,  9642,  8831,  1012,  1030, 12944,  2059,  1011,  1057,
          1012,  1055,  1012,  3187,  1997,  2110, 18748,  2011, 26000,  2140,
         11794,  1005,  1055,  3247,  2000,  4604,  3629,  2046, 13491,  1999,
          3339,  1030, 12944,  7618,  2121,  8615,  2009,  2052, 10083,  2010,
          3488,  2005,  3088,  1998,  2359,  2000,  2128,  9080, 13143,  1030,
         12944,  3881,  2039,  3488,  1999,  3299,  2000,  2886,  8831,  1998,
          2510, 14111,  1999,  7394,  1030, 12944,  1005,  1045,  2052,  2022,
          1999,  5684,  1997, 18856, 16429,  5677,  2075,  2068,  1010,  1005,
          7618,  2121,  2056,  1010,  2429,  2000,  1996,  5491,  1030, 12944,
          3488,  2196,  2724, 16453,  2004,  5261,  5708,  2001,  2700, 10760,
          9530,  3436, 11916,  3488, 14801,  2510,  7047,  2013, 10851, 22011,
          9642,  3719,  4755,  3629,  1998,  2162,  3430,  2000, 14369, 18886,
          9681,  2114,  7394,  7888,  1998, 25278,  1012])

" run Cl ser Cl visit anythingederal member 58 fall center Han alone disorders homosure En emailreetief carry minduments fraudters DEA Don comesput## age ret serching anythingBl mind Audioters gen mind Element 120045 Britain Sar-> opinions Clattle Assached sum Sonters 58 fall couples cut veh Ang mind...alogtersacht video net customers Currentarrattle triedaffHowput run Cl ser Cl pick planning Clommactive video fraud ret ser briefselves produce revealsppingputoke anything help Swed German ; video issue Kickstarter comes fire yes.' experience someone acquises109 olderputepend Qu Clattle help repl anything Han alone disorders hom video groupstersigure lyricsien helpraelEnglish mind slicrollingpread experience opposition anything unlsect Clganoub University take run Cl ser Cl visit anythingederalilitary Mycollashingalog ret serraz mindligBl fire Audioattle pleganoub 58 fall cos investigches 87 net hom cut tried experienceduct mind sound entitledMartganoub rock En homattleication minduments

In [42]:
for i in range(20):
    print(i, " -> ", ds.passages[i])

0  ->  The harrowing stories of women and children locked up for so-called 'moral crimes' in Afghanistan's notorious female prison have been revealed after cameras were allowed inside. Mariam has been in Badam Bagh prison for three months after she shot a man who just raped her at gunpoint and then turned the weapon on herself - but she has yet to been charged. Nuria has eight months left to serve of her sentence for trying to divorce her husband. She gave birth in prison to her son and they share a cell together. Scroll down for video Nuria was jailed for trying to divorce her husband. Her son is one of 62 children living at Badam Bagh prison
@highlight
Most of the 202 Badam Bagh inmates are jailed for so-called 'moral crimes'
@highlight
Crimes include leaving their husbands or refusing an arrange marriage
@highlight
62 children live there and share cells with their mothers and five others
1  ->  Caracas, Venezuela (CNN) -- It's been more than 180 years since Venezuelans saw Simon Bol

In [43]:
list(filter(lambda x: x.query.startswith("the continge"), ds.question_answer_objs))

[]

In [44]:
from training import train_LLM
from transformers import GPT2Tokenizer
from datasets import Boolq_dataset
from dataset_loaders import load_boolq
from models import Model_LLM
from transformers import GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
boolq_dataset = load_boolq("raw_data/BoolQ/train.jsonl", tokenizer)
eval_boolq_dataset = load_boolq("raw_data/BoolQ/dev.jsonl", tokenizer)

base_model = GPT2LMHeadModel.from_pretrained('gpt2')
model = Model_LLM(base_model, tokenizer)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)

In [ ]:
train_LLM(model=model, optimizer=optimizer, dataset=boolq_dataset, eval_dataset=eval_boolq_dataset, epochs=1, batch_size=1)